//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemMOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Court()
        {
            this.CourtsOffices = new HashSet<CourtsOffice>();
            this.Users = new HashSet<User>();
        }
    
        public int CourtID { get; set; }
        public string CourtName { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> AllowAppointment { get; set; }
        public Nullable<int> AppointmentLimit { get; set; }
        public Nullable<int> CourtCode { get; set; }
        public string CityCode { get; set; }
        public string RegionCode { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OldCourtId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourtsOffice> CourtsOffices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
