//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemMOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourtsOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourtsOffice()
        {
            this.Users_Courts = new HashSet<Users_Courts>();
        }
    
        public int Id { get; set; }
        public string OfficeName { get; set; }
        public int OfficeNo { get; set; }
        public int CourtId { get; set; }
        public Nullable<int> WorkPercentage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsWorking { get; set; }
    
        public virtual Court Court { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Courts> Users_Courts { get; set; }
    }
}
