//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemMOJ.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOJEntities : DbContext
    {
        public MOJEntities()
            : base("name=MOJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Court> Courts { get; set; }
        public virtual DbSet<CourtsOffice> CourtsOffices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SubRole> SubRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Users_Courts> Users_Courts { get; set; }
    }
}
