//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportSystemMOJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Users_Courts = new HashSet<Users_Courts>();
            this.Users_Courts1 = new HashSet<Users_Courts>();
            this.Users_Courts2 = new HashSet<Users_Courts>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> CourtID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<int> OfficeNumber { get; set; }
        public Nullable<int> OfficeFloorNumber { get; set; }
        public string OfficeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsInworkToday { get; set; }
        public Nullable<int> MaxQueueCount { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string SocialID { get; set; }
        public string ExtensionNumber { get; set; }
        public string ActiveDirectoryUserName { get; set; }
        public Nullable<int> olduserid { get; set; }
        public Nullable<int> SubRoleID { get; set; }
    
        public virtual Court Court { get; set; }
        public virtual Role Role { get; set; }
        public virtual SubRole SubRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Courts> Users_Courts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Courts> Users_Courts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_Courts> Users_Courts2 { get; set; }
    }
}
